# -*- coding: utf-8 -*-
# pylint: disable=unsubscriptable-object,unused-import
from anki.lang import _
# Form implementation generated from reading ui file 'designer/AdvancedStylerUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(862, 671)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 40, 901, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 4, 841, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.saveButton = QtWidgets.QPushButton(self.layoutWidget)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_6.addWidget(self.saveButton)
        self.undoAllButton = QtWidgets.QPushButton(self.layoutWidget)
        self.undoAllButton.setObjectName("undoAllButton")
        self.horizontalLayout_6.addWidget(self.undoAllButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.cancelButton = QtWidgets.QPushButton(self.layoutWidget)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_6.addWidget(self.cancelButton)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 60, 421, 605))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.cardGroupBox = QtWidgets.QGroupBox(self.layoutWidget1)
        self.cardGroupBox.setCheckable(True)
        self.cardGroupBox.setChecked(True)
        self.cardGroupBox.setObjectName("cardGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.cardGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.cardGroupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.sizeSpinBox = QtWidgets.QSpinBox(self.cardGroupBox)
        self.sizeSpinBox.setMaximum(999)
        self.sizeSpinBox.setObjectName("sizeSpinBox")
        self.horizontalLayout_2.addWidget(self.sizeSpinBox)
        self.label_7 = QtWidgets.QLabel(self.cardGroupBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.cardGroupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.alignLeft = QtWidgets.QRadioButton(self.cardGroupBox)
        self.alignLeft.setObjectName("alignLeft")
        self.horizontalLayout_5.addWidget(self.alignLeft)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.alignCenter = QtWidgets.QRadioButton(self.cardGroupBox)
        self.alignCenter.setObjectName("alignCenter")
        self.horizontalLayout_5.addWidget(self.alignCenter)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.alignRight = QtWidgets.QRadioButton(self.cardGroupBox)
        self.alignRight.setObjectName("alignRight")
        self.horizontalLayout_5.addWidget(self.alignRight)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.cardGroupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.cardBGColor = QtWidgets.QLineEdit(self.cardGroupBox)
        self.cardBGColor.setObjectName("cardBGColor")
        self.horizontalLayout_4.addWidget(self.cardBGColor)
        self.cardBGColorbutton = QtWidgets.QToolButton(self.cardGroupBox)
        self.cardBGColorbutton.setObjectName("cardBGColorbutton")
        self.horizontalLayout_4.addWidget(self.cardBGColorbutton)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.cardGroupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.cardTextColor = QtWidgets.QLineEdit(self.cardGroupBox)
        self.cardTextColor.setObjectName("cardTextColor")
        self.horizontalLayout_3.addWidget(self.cardTextColor)
        self.cardTextColorButton = QtWidgets.QToolButton(self.cardGroupBox)
        self.cardTextColorButton.setObjectName("cardTextColorButton")
        self.horizontalLayout_3.addWidget(self.cardTextColorButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.cardGroupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.fontComboBox = QtWidgets.QFontComboBox(self.cardGroupBox)
        self.fontComboBox.setObjectName("fontComboBox")
        self.horizontalLayout.addWidget(self.fontComboBox)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.enableCardMaxWidth = QtWidgets.QCheckBox(self.cardGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enableCardMaxWidth.sizePolicy().hasHeightForWidth())
        self.enableCardMaxWidth.setSizePolicy(sizePolicy)
        self.enableCardMaxWidth.setObjectName("enableCardMaxWidth")
        self.horizontalLayout_37.addWidget(self.enableCardMaxWidth)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem8)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.cardWidthPercetRadioButton = QtWidgets.QRadioButton(self.cardGroupBox)
        self.cardWidthPercetRadioButton.setText("")
        self.cardWidthPercetRadioButton.setAutoExclusive(False)
        self.cardWidthPercetRadioButton.setObjectName("cardWidthPercetRadioButton")
        self.horizontalLayout_38.addWidget(self.cardWidthPercetRadioButton)
        self.cardWidthPerectSpinBox = QtWidgets.QSpinBox(self.cardGroupBox)
        self.cardWidthPerectSpinBox.setMaximum(999)
        self.cardWidthPerectSpinBox.setObjectName("cardWidthPerectSpinBox")
        self.horizontalLayout_38.addWidget(self.cardWidthPerectSpinBox)
        self.label_32 = QtWidgets.QLabel(self.cardGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_38.addWidget(self.label_32)
        self.horizontalLayout_37.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.cardWidthPixelRadioButton = QtWidgets.QRadioButton(self.cardGroupBox)
        self.cardWidthPixelRadioButton.setText("")
        self.cardWidthPixelRadioButton.setAutoExclusive(False)
        self.cardWidthPixelRadioButton.setObjectName("cardWidthPixelRadioButton")
        self.horizontalLayout_39.addWidget(self.cardWidthPixelRadioButton)
        self.cardWidthPixelSpinBox = QtWidgets.QSpinBox(self.cardGroupBox)
        self.cardWidthPixelSpinBox.setMaximum(9999)
        self.cardWidthPixelSpinBox.setObjectName("cardWidthPixelSpinBox")
        self.horizontalLayout_39.addWidget(self.cardWidthPixelSpinBox)
        self.label_33 = QtWidgets.QLabel(self.cardGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_39.addWidget(self.label_33)
        self.horizontalLayout_37.addLayout(self.horizontalLayout_39)
        self.gridLayout_2.addLayout(self.horizontalLayout_37, 5, 0, 1, 1)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.enableCardMargin = QtWidgets.QCheckBox(self.cardGroupBox)
        self.enableCardMargin.setObjectName("enableCardMargin")
        self.horizontalLayout_40.addWidget(self.enableCardMargin)
        self.cardMarginCenterRadio = QtWidgets.QRadioButton(self.cardGroupBox)
        self.cardMarginCenterRadio.setAutoExclusive(False)
        self.cardMarginCenterRadio.setObjectName("cardMarginCenterRadio")
        self.horizontalLayout_40.addWidget(self.cardMarginCenterRadio)
        self.cardMarginCustomRadio = QtWidgets.QRadioButton(self.cardGroupBox)
        self.cardMarginCustomRadio.setText("")
        self.cardMarginCustomRadio.setAutoExclusive(False)
        self.cardMarginCustomRadio.setObjectName("cardMarginCustomRadio")
        self.horizontalLayout_40.addWidget(self.cardMarginCustomRadio)
        self.cardMarginCustom = QtWidgets.QLineEdit(self.cardGroupBox)
        self.cardMarginCustom.setObjectName("cardMarginCustom")
        self.horizontalLayout_40.addWidget(self.cardMarginCustom)
        self.gridLayout_2.addLayout(self.horizontalLayout_40, 6, 0, 1, 1)
        self.cardWordWrapCheckBox = QtWidgets.QCheckBox(self.cardGroupBox)
        self.cardWordWrapCheckBox.setObjectName("cardWordWrapCheckBox")
        self.gridLayout_2.addWidget(self.cardWordWrapCheckBox, 7, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.cardGroupBox)
        self.generalGroupBox = QtWidgets.QGroupBox(self.layoutWidget1)
        self.generalGroupBox.setCheckable(True)
        self.generalGroupBox.setObjectName("generalGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.generalGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.enableUnderlined = QtWidgets.QCheckBox(self.generalGroupBox)
        self.enableUnderlined.setText("")
        self.enableUnderlined.setChecked(False)
        self.enableUnderlined.setObjectName("enableUnderlined")
        self.gridLayout.addWidget(self.enableUnderlined, 4, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_11 = QtWidgets.QLabel(self.generalGroupBox)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_18.addWidget(self.label_11)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.underlinedBoldCBOX = QtWidgets.QCheckBox(self.generalGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.underlinedBoldCBOX.setFont(font)
        self.underlinedBoldCBOX.setChecked(False)
        self.underlinedBoldCBOX.setObjectName("underlinedBoldCBOX")
        self.horizontalLayout_20.addWidget(self.underlinedBoldCBOX)
        self.underlinedItalicBox = QtWidgets.QCheckBox(self.generalGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.underlinedItalicBox.setFont(font)
        self.underlinedItalicBox.setObjectName("underlinedItalicBox")
        self.horizontalLayout_20.addWidget(self.underlinedItalicBox)
        self.underlinedUnderlinedBox = QtWidgets.QCheckBox(self.generalGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.underlinedUnderlinedBox.setFont(font)
        self.underlinedUnderlinedBox.setChecked(False)
        self.underlinedUnderlinedBox.setObjectName("underlinedUnderlinedBox")
        self.horizontalLayout_20.addWidget(self.underlinedUnderlinedBox)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_17 = QtWidgets.QLabel(self.generalGroupBox)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_19.addWidget(self.label_17)
        self.underlinedTextColor = QtWidgets.QLineEdit(self.generalGroupBox)
        self.underlinedTextColor.setObjectName("underlinedTextColor")
        self.horizontalLayout_19.addWidget(self.underlinedTextColor)
        self.underlinedTextColorButton = QtWidgets.QToolButton(self.generalGroupBox)
        self.underlinedTextColorButton.setObjectName("underlinedTextColorButton")
        self.horizontalLayout_19.addWidget(self.underlinedTextColorButton)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_19)
        self.verticalLayout_4.addLayout(self.horizontalLayout_20)
        self.gridLayout.addLayout(self.verticalLayout_4, 4, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.generalGroupBox)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 3, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_8 = QtWidgets.QLabel(self.generalGroupBox)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_14.addWidget(self.label_8)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.boldBoldCBOX = QtWidgets.QCheckBox(self.generalGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.boldBoldCBOX.setFont(font)
        self.boldBoldCBOX.setChecked(False)
        self.boldBoldCBOX.setObjectName("boldBoldCBOX")
        self.horizontalLayout_9.addWidget(self.boldBoldCBOX)
        self.boldItalicBox = QtWidgets.QCheckBox(self.generalGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.boldItalicBox.setFont(font)
        self.boldItalicBox.setObjectName("boldItalicBox")
        self.horizontalLayout_9.addWidget(self.boldItalicBox)
        self.boldUnderlinedBox = QtWidgets.QCheckBox(self.generalGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.boldUnderlinedBox.setFont(font)
        self.boldUnderlinedBox.setObjectName("boldUnderlinedBox")
        self.horizontalLayout_9.addWidget(self.boldUnderlinedBox)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_12 = QtWidgets.QLabel(self.generalGroupBox)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.boldTextColor = QtWidgets.QLineEdit(self.generalGroupBox)
        self.boldTextColor.setObjectName("boldTextColor")
        self.horizontalLayout_7.addWidget(self.boldTextColor)
        self.boldTextColorButton = QtWidgets.QToolButton(self.generalGroupBox)
        self.boldTextColorButton.setObjectName("boldTextColorButton")
        self.horizontalLayout_7.addWidget(self.boldTextColorButton)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.generalGroupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 1, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.generalGroupBox)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 5, 1, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_18 = QtWidgets.QLabel(self.generalGroupBox)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_21.addWidget(self.label_18)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem11)
        self.verticalLayout_5.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.linksBoldCBOX = QtWidgets.QCheckBox(self.generalGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.linksBoldCBOX.setFont(font)
        self.linksBoldCBOX.setChecked(False)
        self.linksBoldCBOX.setObjectName("linksBoldCBOX")
        self.horizontalLayout_23.addWidget(self.linksBoldCBOX)
        self.linksItalicBox = QtWidgets.QCheckBox(self.generalGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.linksItalicBox.setFont(font)
        self.linksItalicBox.setObjectName("linksItalicBox")
        self.horizontalLayout_23.addWidget(self.linksItalicBox)
        self.linksUnderlinedBox = QtWidgets.QCheckBox(self.generalGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.linksUnderlinedBox.setFont(font)
        self.linksUnderlinedBox.setObjectName("linksUnderlinedBox")
        self.horizontalLayout_23.addWidget(self.linksUnderlinedBox)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_19 = QtWidgets.QLabel(self.generalGroupBox)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_22.addWidget(self.label_19)
        self.linksTextColor = QtWidgets.QLineEdit(self.generalGroupBox)
        self.linksTextColor.setObjectName("linksTextColor")
        self.horizontalLayout_22.addWidget(self.linksTextColor)
        self.linksTextColorButton = QtWidgets.QToolButton(self.generalGroupBox)
        self.linksTextColorButton.setObjectName("linksTextColorButton")
        self.horizontalLayout_22.addWidget(self.linksTextColorButton)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_22)
        self.verticalLayout_5.addLayout(self.horizontalLayout_23)
        self.gridLayout.addLayout(self.verticalLayout_5, 6, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_10 = QtWidgets.QLabel(self.generalGroupBox)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_16.addWidget(self.label_10)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem12)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.italicsBoldCBOX = QtWidgets.QCheckBox(self.generalGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.italicsBoldCBOX.setFont(font)
        self.italicsBoldCBOX.setChecked(False)
        self.italicsBoldCBOX.setObjectName("italicsBoldCBOX")
        self.horizontalLayout_17.addWidget(self.italicsBoldCBOX)
        self.italicsItalicBox = QtWidgets.QCheckBox(self.generalGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.italicsItalicBox.setFont(font)
        self.italicsItalicBox.setChecked(False)
        self.italicsItalicBox.setObjectName("italicsItalicBox")
        self.horizontalLayout_17.addWidget(self.italicsItalicBox)
        self.italicsUnderlinedBox = QtWidgets.QCheckBox(self.generalGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.italicsUnderlinedBox.setFont(font)
        self.italicsUnderlinedBox.setObjectName("italicsUnderlinedBox")
        self.horizontalLayout_17.addWidget(self.italicsUnderlinedBox)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_16 = QtWidgets.QLabel(self.generalGroupBox)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_12.addWidget(self.label_16)
        self.italicsTextColor = QtWidgets.QLineEdit(self.generalGroupBox)
        self.italicsTextColor.setObjectName("italicsTextColor")
        self.horizontalLayout_12.addWidget(self.italicsTextColor)
        self.italicsTextColorButton = QtWidgets.QToolButton(self.generalGroupBox)
        self.italicsTextColorButton.setObjectName("italicsTextColorButton")
        self.horizontalLayout_12.addWidget(self.italicsTextColorButton)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_12)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.gridLayout.addLayout(self.verticalLayout_3, 2, 1, 1, 1)
        self.enableItalics = QtWidgets.QCheckBox(self.generalGroupBox)
        self.enableItalics.setText("")
        self.enableItalics.setChecked(False)
        self.enableItalics.setObjectName("enableItalics")
        self.gridLayout.addWidget(self.enableItalics, 2, 0, 1, 1)
        self.enableBold = QtWidgets.QCheckBox(self.generalGroupBox)
        self.enableBold.setText("")
        self.enableBold.setChecked(False)
        self.enableBold.setObjectName("enableBold")
        self.gridLayout.addWidget(self.enableBold, 0, 0, 1, 1)
        self.enableLinks = QtWidgets.QCheckBox(self.generalGroupBox)
        self.enableLinks.setText("")
        self.enableLinks.setChecked(False)
        self.enableLinks.setObjectName("enableLinks")
        self.gridLayout.addWidget(self.enableLinks, 6, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.generalGroupBox)
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(440, 60, 411, 599))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.clozeGroupBox = QtWidgets.QGroupBox(self.layoutWidget2)
        self.clozeGroupBox.setCheckable(True)
        self.clozeGroupBox.setObjectName("clozeGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.clozeGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_14 = QtWidgets.QLabel(self.clozeGroupBox)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_10.addWidget(self.label_14)
        self.clozeBoldCBOX = QtWidgets.QCheckBox(self.clozeGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.clozeBoldCBOX.setFont(font)
        self.clozeBoldCBOX.setChecked(False)
        self.clozeBoldCBOX.setObjectName("clozeBoldCBOX")
        self.horizontalLayout_10.addWidget(self.clozeBoldCBOX)
        self.clozeItalicBox = QtWidgets.QCheckBox(self.clozeGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.clozeItalicBox.setFont(font)
        self.clozeItalicBox.setObjectName("clozeItalicBox")
        self.horizontalLayout_10.addWidget(self.clozeItalicBox)
        self.clozeUnderlinedBox = QtWidgets.QCheckBox(self.clozeGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.clozeUnderlinedBox.setFont(font)
        self.clozeUnderlinedBox.setObjectName("clozeUnderlinedBox")
        self.horizontalLayout_10.addWidget(self.clozeUnderlinedBox)
        self.clozeSizeSpinBox = QtWidgets.QSpinBox(self.clozeGroupBox)
        self.clozeSizeSpinBox.setMaximum(999)
        self.clozeSizeSpinBox.setObjectName("clozeSizeSpinBox")
        self.horizontalLayout_10.addWidget(self.clozeSizeSpinBox)
        self.label_23 = QtWidgets.QLabel(self.clozeGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_10.addWidget(self.label_23)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.clozeGroupBox)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem13)
        self.clozeTextColor = QtWidgets.QLineEdit(self.clozeGroupBox)
        self.clozeTextColor.setObjectName("clozeTextColor")
        self.horizontalLayout_8.addWidget(self.clozeTextColor)
        self.clozeTextColorButton = QtWidgets.QToolButton(self.clozeGroupBox)
        self.clozeTextColorButton.setObjectName("clozeTextColorButton")
        self.horizontalLayout_8.addWidget(self.clozeTextColorButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_9 = QtWidgets.QLabel(self.clozeGroupBox)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem14)
        self.clozeBGColor = QtWidgets.QLineEdit(self.clozeGroupBox)
        self.clozeBGColor.setObjectName("clozeBGColor")
        self.horizontalLayout_11.addWidget(self.clozeBGColor)
        self.clozeBGColorButton = QtWidgets.QToolButton(self.clozeGroupBox)
        self.clozeBGColorButton.setObjectName("clozeBGColorButton")
        self.horizontalLayout_11.addWidget(self.clozeBGColorButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.verticalLayout_9.addWidget(self.clozeGroupBox)
        self.extraGroupBox = QtWidgets.QGroupBox(self.layoutWidget2)
        self.extraGroupBox.setCheckable(True)
        self.extraGroupBox.setObjectName("extraGroupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.extraGroupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_15 = QtWidgets.QLabel(self.extraGroupBox)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_13.addWidget(self.label_15)
        self.extraBoldCBOX = QtWidgets.QCheckBox(self.extraGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.extraBoldCBOX.setFont(font)
        self.extraBoldCBOX.setChecked(False)
        self.extraBoldCBOX.setObjectName("extraBoldCBOX")
        self.horizontalLayout_13.addWidget(self.extraBoldCBOX)
        self.extraUnderlinedBox = QtWidgets.QCheckBox(self.extraGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.extraUnderlinedBox.setFont(font)
        self.extraUnderlinedBox.setObjectName("extraUnderlinedBox")
        self.horizontalLayout_13.addWidget(self.extraUnderlinedBox)
        self.extraItalicBox = QtWidgets.QCheckBox(self.extraGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.extraItalicBox.setFont(font)
        self.extraItalicBox.setObjectName("extraItalicBox")
        self.horizontalLayout_13.addWidget(self.extraItalicBox)
        self.extraSizeSpinBox = QtWidgets.QSpinBox(self.extraGroupBox)
        self.extraSizeSpinBox.setMaximum(999)
        self.extraSizeSpinBox.setObjectName("extraSizeSpinBox")
        self.horizontalLayout_13.addWidget(self.extraSizeSpinBox)
        self.label_22 = QtWidgets.QLabel(self.extraGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_13.addWidget(self.label_22)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_20 = QtWidgets.QLabel(self.extraGroupBox)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_15.addWidget(self.label_20)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem15)
        self.extraTextColor = QtWidgets.QLineEdit(self.extraGroupBox)
        self.extraTextColor.setObjectName("extraTextColor")
        self.horizontalLayout_15.addWidget(self.extraTextColor)
        self.extraTextColorButton = QtWidgets.QToolButton(self.extraGroupBox)
        self.extraTextColorButton.setObjectName("extraTextColorButton")
        self.horizontalLayout_15.addWidget(self.extraTextColorButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_21 = QtWidgets.QLabel(self.extraGroupBox)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_24.addWidget(self.label_21)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem16)
        self.extraBGColor = QtWidgets.QLineEdit(self.extraGroupBox)
        self.extraBGColor.setObjectName("extraBGColor")
        self.horizontalLayout_24.addWidget(self.extraBGColor)
        self.extraBGColorButton = QtWidgets.QToolButton(self.extraGroupBox)
        self.extraBGColorButton.setObjectName("extraBGColorButton")
        self.horizontalLayout_24.addWidget(self.extraBGColorButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_24)
        self.verticalLayout_9.addWidget(self.extraGroupBox)
        self.imageGroupBox = QtWidgets.QGroupBox(self.layoutWidget2)
        self.imageGroupBox.setFlat(False)
        self.imageGroupBox.setCheckable(True)
        self.imageGroupBox.setObjectName("imageGroupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.imageGroupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_24 = QtWidgets.QLabel(self.imageGroupBox)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_32.addWidget(self.label_24)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem17)
        self.noneDisplayRadioButton = QtWidgets.QRadioButton(self.imageGroupBox)
        self.noneDisplayRadioButton.setAutoExclusive(True)
        self.noneDisplayRadioButton.setObjectName("noneDisplayRadioButton")
        self.horizontalLayout_32.addWidget(self.noneDisplayRadioButton)
        self.imgBlockDisplayRadioButton = QtWidgets.QRadioButton(self.imageGroupBox)
        self.imgBlockDisplayRadioButton.setAutoExclusive(True)
        self.imgBlockDisplayRadioButton.setObjectName("imgBlockDisplayRadioButton")
        self.horizontalLayout_32.addWidget(self.imgBlockDisplayRadioButton)
        self.imgInlineDisplayRadioButton = QtWidgets.QRadioButton(self.imageGroupBox)
        self.imgInlineDisplayRadioButton.setAutoExclusive(True)
        self.imgInlineDisplayRadioButton.setObjectName("imgInlineDisplayRadioButton")
        self.horizontalLayout_32.addWidget(self.imgInlineDisplayRadioButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.enableImgMaxWidth = QtWidgets.QCheckBox(self.imageGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enableImgMaxWidth.sizePolicy().hasHeightForWidth())
        self.enableImgMaxWidth.setSizePolicy(sizePolicy)
        self.enableImgMaxWidth.setObjectName("enableImgMaxWidth")
        self.horizontalLayout_27.addWidget(self.enableImgMaxWidth)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem18)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.imgWidthPercetRadioButton = QtWidgets.QRadioButton(self.imageGroupBox)
        self.imgWidthPercetRadioButton.setText("")
        self.imgWidthPercetRadioButton.setAutoExclusive(True)
        self.imgWidthPercetRadioButton.setObjectName("imgWidthPercetRadioButton")
        self.horizontalLayout_25.addWidget(self.imgWidthPercetRadioButton)
        self.imgWidthPerectSpinBox = QtWidgets.QSpinBox(self.imageGroupBox)
        self.imgWidthPerectSpinBox.setMaximum(999)
        self.imgWidthPerectSpinBox.setObjectName("imgWidthPerectSpinBox")
        self.horizontalLayout_25.addWidget(self.imgWidthPerectSpinBox)
        self.label_30 = QtWidgets.QLabel(self.imageGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_25.addWidget(self.label_30)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.imgWidthPixelRadioButton = QtWidgets.QRadioButton(self.imageGroupBox)
        self.imgWidthPixelRadioButton.setText("")
        self.imgWidthPixelRadioButton.setAutoExclusive(True)
        self.imgWidthPixelRadioButton.setObjectName("imgWidthPixelRadioButton")
        self.horizontalLayout_26.addWidget(self.imgWidthPixelRadioButton)
        self.imgWidthPixelSpinBox = QtWidgets.QSpinBox(self.imageGroupBox)
        self.imgWidthPixelSpinBox.setMaximum(9999)
        self.imgWidthPixelSpinBox.setObjectName("imgWidthPixelSpinBox")
        self.horizontalLayout_26.addWidget(self.imgWidthPixelSpinBox)
        self.label_31 = QtWidgets.QLabel(self.imageGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_26.addWidget(self.label_31)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_26)
        self.verticalLayout_7.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.enableImgMaxHeight = QtWidgets.QCheckBox(self.imageGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enableImgMaxHeight.sizePolicy().hasHeightForWidth())
        self.enableImgMaxHeight.setSizePolicy(sizePolicy)
        self.enableImgMaxHeight.setObjectName("enableImgMaxHeight")
        self.horizontalLayout_29.addWidget(self.enableImgMaxHeight)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem19)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.imgHeightPercetRadioButton = QtWidgets.QRadioButton(self.imageGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgHeightPercetRadioButton.sizePolicy().hasHeightForWidth())
        self.imgHeightPercetRadioButton.setSizePolicy(sizePolicy)
        self.imgHeightPercetRadioButton.setText("")
        self.imgHeightPercetRadioButton.setAutoExclusive(False)
        self.imgHeightPercetRadioButton.setObjectName("imgHeightPercetRadioButton")
        self.horizontalLayout_30.addWidget(self.imgHeightPercetRadioButton)
        self.imgHeightPerectSpinBox = QtWidgets.QSpinBox(self.imageGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgHeightPerectSpinBox.sizePolicy().hasHeightForWidth())
        self.imgHeightPerectSpinBox.setSizePolicy(sizePolicy)
        self.imgHeightPerectSpinBox.setMaximum(999)
        self.imgHeightPerectSpinBox.setObjectName("imgHeightPerectSpinBox")
        self.horizontalLayout_30.addWidget(self.imgHeightPerectSpinBox)
        self.label_34 = QtWidgets.QLabel(self.imageGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_30.addWidget(self.label_34)
        self.horizontalLayout_29.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.imgHeightPixelRadioButton = QtWidgets.QRadioButton(self.imageGroupBox)
        self.imgHeightPixelRadioButton.setText("")
        self.imgHeightPixelRadioButton.setAutoExclusive(False)
        self.imgHeightPixelRadioButton.setObjectName("imgHeightPixelRadioButton")
        self.horizontalLayout_31.addWidget(self.imgHeightPixelRadioButton)
        self.imgHeightPixelSpinBox = QtWidgets.QSpinBox(self.imageGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgHeightPixelSpinBox.sizePolicy().hasHeightForWidth())
        self.imgHeightPixelSpinBox.setSizePolicy(sizePolicy)
        self.imgHeightPixelSpinBox.setMaximum(9999)
        self.imgHeightPixelSpinBox.setObjectName("imgHeightPixelSpinBox")
        self.horizontalLayout_31.addWidget(self.imgHeightPixelSpinBox)
        self.label_35 = QtWidgets.QLabel(self.imageGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_31.addWidget(self.label_35)
        self.horizontalLayout_29.addLayout(self.horizontalLayout_31)
        self.verticalLayout_7.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.enableImgBorder = QtWidgets.QCheckBox(self.imageGroupBox)
        self.enableImgBorder.setObjectName("enableImgBorder")
        self.horizontalLayout_35.addWidget(self.enableImgBorder)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.imgBorderPixelSpinBox = QtWidgets.QSpinBox(self.imageGroupBox)
        self.imgBorderPixelSpinBox.setMaximum(999)
        self.imgBorderPixelSpinBox.setObjectName("imgBorderPixelSpinBox")
        self.horizontalLayout_34.addWidget(self.imgBorderPixelSpinBox)
        self.label_36 = QtWidgets.QLabel(self.imageGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_34.addWidget(self.label_36)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_26 = QtWidgets.QLabel(self.imageGroupBox)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_33.addWidget(self.label_26)
        self.imgBorderColor = QtWidgets.QLineEdit(self.imageGroupBox)
        self.imgBorderColor.setObjectName("imgBorderColor")
        self.horizontalLayout_33.addWidget(self.imgBorderColor)
        self.imgBorderColorButton = QtWidgets.QToolButton(self.imageGroupBox)
        self.imgBorderColorButton.setObjectName("imgBorderColorButton")
        self.horizontalLayout_33.addWidget(self.imgBorderColorButton)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_33)
        self.verticalLayout_7.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.enableImgShadow = QtWidgets.QCheckBox(self.imageGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enableImgShadow.sizePolicy().hasHeightForWidth())
        self.enableImgShadow.setSizePolicy(sizePolicy)
        self.enableImgShadow.setObjectName("enableImgShadow")
        self.horizontalLayout_28.addWidget(self.enableImgShadow)
        self.imgShadowDropRadioButton = QtWidgets.QRadioButton(self.imageGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgShadowDropRadioButton.sizePolicy().hasHeightForWidth())
        self.imgShadowDropRadioButton.setSizePolicy(sizePolicy)
        self.imgShadowDropRadioButton.setAutoExclusive(False)
        self.imgShadowDropRadioButton.setObjectName("imgShadowDropRadioButton")
        self.horizontalLayout_28.addWidget(self.imgShadowDropRadioButton)
        self.imgShadowGlowRadioButton = QtWidgets.QRadioButton(self.imageGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgShadowGlowRadioButton.sizePolicy().hasHeightForWidth())
        self.imgShadowGlowRadioButton.setSizePolicy(sizePolicy)
        self.imgShadowGlowRadioButton.setAutoExclusive(False)
        self.imgShadowGlowRadioButton.setObjectName("imgShadowGlowRadioButton")
        self.horizontalLayout_28.addWidget(self.imgShadowGlowRadioButton)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_27 = QtWidgets.QLabel(self.imageGroupBox)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_36.addWidget(self.label_27)
        self.imgShadowColor = QtWidgets.QLineEdit(self.imageGroupBox)
        self.imgShadowColor.setObjectName("imgShadowColor")
        self.horizontalLayout_36.addWidget(self.imgShadowColor)
        self.imgShadowColorButton = QtWidgets.QToolButton(self.imageGroupBox)
        self.imgShadowColorButton.setObjectName("imgShadowColorButton")
        self.horizontalLayout_36.addWidget(self.imgShadowColorButton)
        self.horizontalLayout_28.addLayout(self.horizontalLayout_36)
        self.verticalLayout_7.addLayout(self.horizontalLayout_28)
        self.verticalLayout_9.addWidget(self.imageGroupBox)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.extraTagButton = QtWidgets.QPushButton(self.groupBox)
        self.extraTagButton.setObjectName("extraTagButton")
        self.horizontalLayout_42.addWidget(self.extraTagButton)
        self.label_28 = QtWidgets.QLabel(self.groupBox)
        self.label_28.setEnabled(False)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_42.addWidget(self.label_28)
        self.verticalLayout_10.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.timerSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.timerSpinBox.setObjectName("timerSpinBox")
        self.horizontalLayout_41.addWidget(self.timerSpinBox)
        self.label_25 = QtWidgets.QLabel(self.groupBox)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_41.addWidget(self.label_25)
        self.addTimerButton = QtWidgets.QPushButton(self.groupBox)
        self.addTimerButton.setObjectName("addTimerButton")
        self.horizontalLayout_41.addWidget(self.addTimerButton)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_41.addItem(spacerItem20)
        self.removeTimerButton = QtWidgets.QPushButton(self.groupBox)
        self.removeTimerButton.setObjectName("removeTimerButton")
        self.horizontalLayout_41.addWidget(self.removeTimerButton)
        self.verticalLayout_10.addLayout(self.horizontalLayout_41)
        self.verticalLayout_9.addWidget(self.groupBox)
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setEnabled(False)
        self.label.setObjectName("label")
        self.verticalLayout_9.addWidget(self.label)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.saveButton, self.cardGroupBox)
        Form.setTabOrder(self.cardGroupBox, self.fontComboBox)
        Form.setTabOrder(self.fontComboBox, self.sizeSpinBox)
        Form.setTabOrder(self.sizeSpinBox, self.alignLeft)
        Form.setTabOrder(self.alignLeft, self.alignCenter)
        Form.setTabOrder(self.alignCenter, self.alignRight)
        Form.setTabOrder(self.alignRight, self.cardTextColor)
        Form.setTabOrder(self.cardTextColor, self.cardTextColorButton)
        Form.setTabOrder(self.cardTextColorButton, self.cardBGColor)
        Form.setTabOrder(self.cardBGColor, self.cardBGColorbutton)
        Form.setTabOrder(self.cardBGColorbutton, self.generalGroupBox)
        Form.setTabOrder(self.generalGroupBox, self.enableBold)
        Form.setTabOrder(self.enableBold, self.boldTextColor)
        Form.setTabOrder(self.boldTextColor, self.boldTextColorButton)
        Form.setTabOrder(self.boldTextColorButton, self.boldBoldCBOX)
        Form.setTabOrder(self.boldBoldCBOX, self.boldItalicBox)
        Form.setTabOrder(self.boldItalicBox, self.boldUnderlinedBox)
        Form.setTabOrder(self.boldUnderlinedBox, self.enableItalics)
        Form.setTabOrder(self.enableItalics, self.italicsTextColor)
        Form.setTabOrder(self.italicsTextColor, self.italicsTextColorButton)
        Form.setTabOrder(self.italicsTextColorButton, self.italicsBoldCBOX)
        Form.setTabOrder(self.italicsBoldCBOX, self.italicsItalicBox)
        Form.setTabOrder(self.italicsItalicBox, self.italicsUnderlinedBox)
        Form.setTabOrder(self.italicsUnderlinedBox, self.enableUnderlined)
        Form.setTabOrder(self.enableUnderlined, self.underlinedTextColor)
        Form.setTabOrder(self.underlinedTextColor, self.underlinedTextColorButton)
        Form.setTabOrder(self.underlinedTextColorButton, self.underlinedBoldCBOX)
        Form.setTabOrder(self.underlinedBoldCBOX, self.underlinedItalicBox)
        Form.setTabOrder(self.underlinedItalicBox, self.underlinedUnderlinedBox)
        Form.setTabOrder(self.underlinedUnderlinedBox, self.enableLinks)
        Form.setTabOrder(self.enableLinks, self.linksTextColor)
        Form.setTabOrder(self.linksTextColor, self.linksTextColorButton)
        Form.setTabOrder(self.linksTextColorButton, self.linksBoldCBOX)
        Form.setTabOrder(self.linksBoldCBOX, self.linksItalicBox)
        Form.setTabOrder(self.linksItalicBox, self.linksUnderlinedBox)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_("Advanced Card Styler "))
        self.saveButton.setText(_("Preview"))
        self.undoAllButton.setText(_("Undo All"))
        self.cancelButton.setText(_("Accept and Close"))
        self.cardGroupBox.setTitle(_("Card Style"))
        self.label_6.setText(_("Text Size :"))
        self.label_7.setText(_("px"))
        self.label_3.setText(_("Text Align:"))
        self.alignLeft.setText(_("Left"))
        self.alignCenter.setText(_("Center"))
        self.alignRight.setText(_("Right"))
        self.label_5.setText(_("Background Color :"))
        self.cardBGColorbutton.setText(_("..."))
        self.label_4.setText(_("Text Color :"))
        self.cardTextColorButton.setText(_("..."))
        self.label_2.setText(_("Font Family :"))
        self.fontComboBox.setCurrentText(_("Verdana"))
        self.enableCardMaxWidth.setText(_("Max Width :"))
        self.label_32.setText(_("%"))
        self.label_33.setText(_("px"))
        self.enableCardMargin.setText(_("Margin :"))
        self.cardMarginCenterRadio.setToolTip(_("Centers the card in the middle of screen horiontally"))
        self.cardMarginCenterRadio.setText(_("Center"))
        self.cardWordWrapCheckBox.setText(_("Break up long words"))
        self.generalGroupBox.setTitle(_("General Text Style"))
        self.label_11.setText(_("Underlined :"))
        self.underlinedBoldCBOX.setText(_("b"))
        self.underlinedItalicBox.setText(_("i"))
        self.underlinedUnderlinedBox.setText(_("u"))
        self.label_17.setText(_("Color :"))
        self.underlinedTextColorButton.setText(_("..."))
        self.label_8.setText(_("Bold :"))
        self.boldBoldCBOX.setText(_("b"))
        self.boldItalicBox.setText(_("i"))
        self.boldUnderlinedBox.setText(_("u"))
        self.label_12.setText(_("Color :"))
        self.boldTextColorButton.setText(_("..."))
        self.label_18.setText(_("Links :"))
        self.linksBoldCBOX.setText(_("b"))
        self.linksItalicBox.setText(_("i"))
        self.linksUnderlinedBox.setText(_("u"))
        self.label_19.setText(_("Color :"))
        self.linksTextColorButton.setText(_("..."))
        self.label_10.setText(_("Italics :"))
        self.italicsBoldCBOX.setText(_("b"))
        self.italicsItalicBox.setText(_("i"))
        self.italicsUnderlinedBox.setText(_("u"))
        self.label_16.setText(_("Color :"))
        self.italicsTextColorButton.setText(_("..."))
        self.clozeGroupBox.setTitle(_("Cloze Text Style"))
        self.label_14.setText(_("Text Style :"))
        self.clozeBoldCBOX.setText(_("b"))
        self.clozeItalicBox.setText(_("i"))
        self.clozeUnderlinedBox.setText(_("u"))
        self.label_23.setText(_("px"))
        self.label_13.setText(_("Text Color :"))
        self.clozeTextColorButton.setText(_("..."))
        self.label_9.setText(_("Background Color :"))
        self.clozeBGColorButton.setText(_("..."))
        self.extraGroupBox.setTitle(_("Extra Section Style (#extra tag)"))
        self.label_15.setText(_("Text Style :"))
        self.extraBoldCBOX.setText(_("b"))
        self.extraUnderlinedBox.setText(_("u"))
        self.extraItalicBox.setText(_("i"))
        self.label_22.setText(_("px"))
        self.label_20.setText(_("Text Color :"))
        self.extraTextColorButton.setText(_("..."))
        self.label_21.setText(_("Background Color :"))
        self.extraBGColorButton.setText(_("..."))
        self.imageGroupBox.setTitle(_("Image Style"))
        self.label_24.setText(_("Display :"))
        self.noneDisplayRadioButton.setText(_("None (Hide)"))
        self.imgBlockDisplayRadioButton.setToolTip(_("Only one image every line"))
        self.imgBlockDisplayRadioButton.setText(_("Block"))
        self.imgInlineDisplayRadioButton.setToolTip(_("Images can be next to each other on same line"))
        self.imgInlineDisplayRadioButton.setText(_("Inline-block"))
        self.enableImgMaxWidth.setText(_("Max Width :"))
        self.label_30.setText(_("%"))
        self.label_31.setText(_("px"))
        self.enableImgMaxHeight.setText(_("Max Height :"))
        self.label_34.setText(_("%"))
        self.label_35.setText(_("px"))
        self.enableImgBorder.setText(_("Border:"))
        self.label_36.setText(_("px"))
        self.label_26.setText(_("Color:"))
        self.imgBorderColorButton.setText(_("..."))
        self.enableImgShadow.setText(_("Shadow :"))
        self.imgShadowDropRadioButton.setText(_("Drop"))
        self.imgShadowGlowRadioButton.setText(_("Glow"))
        self.label_27.setText(_("Color:"))
        self.imgShadowColorButton.setText(_("..."))
        self.groupBox.setTitle(_("Misc"))
        self.extraTagButton.setText(_("Fix #extra Tag"))
        self.label_28.setText(_("(Use if Extra section not working)"))
        self.label_25.setText(_("seconds"))
        self.addTimerButton.setText(_("Add Timer"))
        self.removeTimerButton.setText(_("Remove Timer"))
        self.label.setText(_("Any fields that are not filled will not be added to the CSS file."))

